language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt

services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('toor') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart

script:
  - pylint app
  - py.test --cov=app/tests/
  - coverage report

after_success:
  - coveralls

notifications:
  email: false
