language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt

services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('toor') where User='root'; update user set plugin='mysql_native_password';"
  - sudo service mysql restart
  - flask db init
  - flask db migrate -m "init"
  - flask db upgrade

script:
  # - pylint app
  - py.test --cov=app/tests/
  - coverage report

after_success:
  - coveralls

notifications:
  email: false
