language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pylint --output-format=text app.py
  - py.test app/tests/test_views.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing --pylint

after_success:
  - coveralls
